export {
  METADATA_EXTRACTION_SYSTEM_PROMPT,
  METADATA_EXTRACTION_USER_PROMPT,
} from './metadata-extraction'

export {
  MODULE_EXTRACTION_SYSTEM_PROMPT,
  MODULE_EXTRACTION_USER_PROMPT,
} from './module-extraction'

export {
  KNOWLEDGE_GRAPH_EXTRACTION_SYSTEM_PROMPT,
  KNOWLEDGE_GRAPH_EXTRACTION_USER_PROMPT,
} from './knowledge-graph-extraction'

export {
  KNOWLEDGE_GRAPH_NODES_SYSTEM_PROMPT,
  KNOWLEDGE_GRAPH_NODES_USER_PROMPT,
} from './knowledge-graph-nodes'

export {
  KNOWLEDGE_GRAPH_EDGES_SYSTEM_PROMPT,
  KNOWLEDGE_GRAPH_EDGES_USER_PROMPT,
} from './knowledge-graph-edges'

export {
  PREREQUISITES_SUGGESTION_SYSTEM_PROMPT,
  PREREQUISITES_SUGGESTION_USER_PROMPT,
} from './prerequisites-suggestion'
